module.exports = {
    OP_INITIALIZE: 0x00,
    OP_REGISTER: 0x01,
    OP_SIGNATURE_R: 0x02,
    OP_SIGNATURE_S: 0x03,
    OP_NOTHING: 0xE0,
    OP_DESTROY_CHILD: 0xF0,
    OP_TERMINATE_NODE: 0xFF,
    ERR_NODE_NOT_FOUND: -1,
    ERR_RIGHTS_NOT_FOUND: -2,
    ERR_USER_NOT_FOUND: -3,
    ERR_SIGNATURE_NOT_FOUND: -4,
    ERR_NODE_NOT_UNIQUE: -5,
    ERR_NO_SUCH_RIGHTS: -6,
    ERR_INSUFFICIENT_FUNDS: -7,
    TRANSACTION_FEE: 0.0001,
    TRANSACTION_AMOUNT: 0.001
};
